TypiconOnline.Web/Models/ScheduleViewModels/ScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TypiconOnline.AppServices.OutputFiltering;
using TypiconOnline.Infrastructure.Common.ErrorHandling;

namespace TypiconOnline.Web.Models.ScheduleViewModels
{
    public class ScheduleViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public DateTime Date { get; set; }
    }
}

TypiconOnline.Web/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
//using SmartBreadcrumbs.Attributes;
using TypiconOnline.AppServices.Interfaces;
using TypiconOnline.AppServices.Messaging.Common;
using TypiconOnline.Domain.Command.Typicon;
using TypiconOnline.Domain.Query.Typicon;
using TypiconOnline.Domain.WebQuery.Models;
using TypiconOnline.AppServices.OutputFiltering;
using TypiconOnline.Domain.WebQuery.Typicon;
using TypiconOnline.Infrastructure.Common.Command;
using TypiconOnline.Infrastructure.Common.ErrorHandling;
using TypiconOnline.Infrastructure.Common.Query;
using TypiconOnline.Web.Models.ScheduleViewModels;
using TypiconOnline.WebServices.Authorization;
using TypiconOnline.Web.Extensions;

namespace TypiconOnline.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Route("[controller]/[action]")]
    [AllowAnonymous]
    public class ScheduleController : Controller
    {
        private const string DEFAULT_LANGUAGE = "cs-ru";

        private const string HTML = "html";
        private const string JSON = "json";

        private readonly IQueryProcessor _queryProcessor;
        private readonly ICommandProcessor _commandProcessor;
        private readonly IScheduleWeekViewer<string> _weekViewer;
        private readonly IScheduleWeekViewer<Result<FileDownloadResponse>> _weekDownloadViewer;
        private readonly IAuthorizationService _authorizationService;
        //private readonly IScheduleDayViewer<string> dayViewer;

        public ScheduleController(IQueryProcessor queryProcessor
            , ICommandProcessor commandProcessor
            //, IScheduleDayViewer<string> dayViewer
            , IScheduleWeekViewer<string> weekViewer
            , IScheduleWeekViewer<Result<FileDownloadResponse>> weekDownloadViewer
            , IAuthorizationService authorizationService)
        {
            _queryProcessor = queryProcessor ?? throw new ArgumentNullException(nameof(queryProcessor));
            _commandProcessor = commandProcessor ?? throw new ArgumentNullException(nameof(commandProcessor));
            _weekViewer = weekViewer ?? throw new ArgumentNullException(nameof(weekViewer));
            _weekDownloadViewer = weekDownloadViewer ?? throw new ArgumentNullException(nameof(weekDownloadViewer));
            _authorizationService = authorizationService ?? throw new ArgumentNullException(nameof(authorizationService));
            //this.dayViewer = dayViewer ?? throw new ArgumentNullException("dayViewer in ScheduleController");
        }

        [Route("{id:int}/{date?}/{language?}")]
        //[Breadcrumb("Устав")] 
        public IActionResult Index(int? id, DateTime date, string language = DEFAULT_LANGUAGE)
        {
            if (id == null)
            {
                return NotFound();
            }
            var typicon = _queryProcessor.Process(new TypiconQuery(id.Value));

            if (typicon.Success)
            {
                if (date == null || date == DateTime.MinValue)
                {
                    date = DateTime.Now;
                }

                return View(new ScheduleViewModel()
                {
                    Id = typicon.Value.Id,
                    Date = date,
                    Language = language,
                    Name = typicon.Value.Name,
                });
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult View(int id, DateTime date, string language = DEFAULT_LANGUAGE)
        {
            //является ли редактором
            bool canEdit = false;
            try
            {
                var typiconEntity = _queryProcessor.Process(new TypiconEntityQuery(id));

                canEdit = _authorizationService.AuthorizeAsync(
                                                           User, typiconEntity,
                                                           TypiconOperations.Edit)
                                               .Result
                                               .Succeeded;
            }
            catch { }

            var weekResult = _queryProcessor.Process(new OutputWeekQuery(id, date, new OutputFilter() { Language = language }));

            object result = null;

            weekResult.OnSuccess(() =>
                {
                    result = new
                    {
                        isEditor = canEdit,
                        schedule = weekResult.Value
                    };
                })
                .OnFailure(err => result = new { err });

            return Json(result);

            //return PartialView("_View", weekResult);
        }

        // GET api/<controller>/getweek/1/01-01-2019
        //[HttpPost]
        [Route("{id}/{date?}/{language?}")]
        public IActionResult Download(int? id, DateTime date, string language = DEFAULT_LANGUAGE)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (date == null || date == DateTime.MinValue)
            {
                date = DateTime.Now;
            }

            var weekResult = _queryProcessor.Process(new OutputWeekQuery(id.Value, date, new OutputFilter() { Language = language }));

            if (weekResult.Success)
            {
                var file = _weekDownloadViewer.Execute(id.Value, weekResult.Value);

                if (file.Success)
                {
                    return File(file.Value.Content, file.Value.ContentType, file.Value.FileDownloadName);
                }
                else
                {
                    //error
                }
            }
            else
            {
                //return weekResult.Error;
            }

            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">TypiconEntity id</param>
        /// <param name="date">Дата</param>
        /// <param name="w">Индекс службы</param>
        /// <returns></returns>
        [HttpGet]
        [Route("{id}/{worshipId}/{filter?}")]
        //[Breadcrumb(Title = "Последовательность", FromAction = "Index")]
        public IActionResult Sequence(int id, int worshipId, OutputFilter filter)
        {
            if (filter == null)
            {
                filter = new OutputFilter() { Language = "cs-ru" };
            }

            var worshipResult = _queryProcessor.Process(new OutputWorshipQuery(worshipId, filter));

            return View(worshipResult);
        }

        /// <summary>
        /// Возвращает Json с расписанием на указанное количество недель
        /// </summary>
        /// <param name="id">Is Устава</param>
        /// <param name="date">Дата</param>
        /// <param name="weeksCount">Количество недель для расписания</param>
        /// <param name="language">Язык локализации</param>
        /// <returns></returns>
        [HttpGet]
        [EnableCors("GetSchedulePolicy")]
        public IActionResult Week(string id, DateTime date, int? weeksCount, string language = DEFAULT_LANGUAGE)
        {
            if (date == null || date == DateTime.MinValue)
            {
                date = DateTime.Now;
            }

            var weeks = GetSchedule(id, date, weeksCount, language);

            object result = null;

            weeks.OnSuccess(() =>
                {
                    Result.Combine(weeks.Value.ToArray<Result>())
                        .OnSuccess(() =>
                        {
                            //Json
                            result = new 
                            { 
                                schedule = weeks
                                    .Value
                                    .Select(c => c.Value.Week) 
                            };
                        })
                        .OnFailure(err => result = new { err });
                })
                .OnFailure(err => result = new { err });

            return Json(result);
        }

        /// <summary>
        /// Возвращает html с расписанием
        /// </summary>
        /// <param name="id"></param>
        /// <param name="weeksCount"></param>
        /// <param name="language"></param>
        /// <returns></returns>
        [HttpGet]
        [EnableCors("GetSchedulePolicy")]
        public IActionResult Html(string id, int? weeksCount = 2, string language = DEFAULT_LANGUAGE)
        {
            string resultString = "";

            var weeks = GetSchedule(id, DateTime.Now, weeksCount, language);

            weeks.OnSuccess(() =>
                {
                    Result.Combine(weeks.Value.ToArray<Result>())
                        .OnSuccess(() =>
                        {
                            //HTML
                            resultString = string
                                        .Join("", weeks.Value.Select(
                                            c => _weekViewer.Execute(c.Value.Id, c.Value.Week)));
                        })
                        .OnFailure(err => resultString = err);
                })
                .OnFailure(err => resultString = err);

            return Content(resultString, "text/html", Encoding.UTF8);
        }

        private Result<List<Result<(int Id, FilteredOutputWeek Week)>>> GetSchedule(string id, DateTime? d, int? weeksCount = 2, string language = DEFAULT_LANGUAGE)
        {
            try
            {
                //date
                var date = d ?? DateTime.Now;

                if ((date.DayOfWeek == DayOfWeek.Sunday) && (date.Hour > 17))
                {
                    date = date.AddDays(1);
                }

                //weeksCount
                if (!weeksCount.HasValue)
                {

TypiconOnline.Web/Views/Schedule/Index.cshtml
@model TypiconOnline.Web.Models.ScheduleViewModels.ScheduleViewModel

@{
    ViewData["Title"] = $"Устав - {Model.Name}";
}

<section>
    <div class="clearfix"></div>
    <div class="row col-sm-12"><h1>Расписание</h1></div>
    <div class="row col-sm-12"><h2>@ViewData["Title"]</h2></div>
    <form id="formSchedule" method="post" class="form-inline" asp-controller="Schedule">
        <div class="form-group">
            <div class="row">
                <div class="col-xs-2">
                    <button id="btnPrev" class="btn btn-default prev" type="button"><span class="fas fa-chevron-left"></span></button>
                </div>
                <div class="col-xs-8">
                    <div class="input-group date" id="datepicker">
                        <input type="text" class="form-control">
                        <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
                    </div>
                    <input type="hidden" id="dtp_date" value="@Model.Date.ToString("yyyy-MM-dd")" name="Date" />
                </div>
                <div class="col-xs-2 text-right">
                    <button id="btnNext" class="btn btn-default next" type="button"><span class="fas fa-chevron-right"></span></button>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-6">
                    <button id="btnView" class="btn btn-default btn-block" type="button"><span id="spanView" class="fas fa-search"></span> Смотреть</button>
                </div>
                <div class="col-xs-6">
                    <button id="btnDownload" class="btn btn-primary btn-block" asp-controller="Schedule" asp-action="Download" asp-route-id="@Model.Id"><span class="fas fa-save"></span> Скачать </button>
                </div>
            </div>
            <input type="hidden" id="typId" value="@Model.Id" name="Id" />
            <input type="hidden" id="language" value="@Model.Language" name="Language" />
        </div>
    </form>
</section>
<section>
    <div class="row">
        <div class="col-sm-12" id="week"></div>
    </div>
</section>

<div class="modal fade editvar-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div id="modalWindow" class="modal-dialog">
    </div>
</div>

@section Scripts {

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="~/css/itemtext.css" />
    <link rel="stylesheet" href="~/css/schedule.css" />
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" />

    <script src="/lib/momentjs/moment-with-locales.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/schedule.js"></script>

    @await Html.PartialAsync("_ValidationScriptsPartial")
}

TypiconOnline.Web/Views/Schedule/Sequence.cshtml
@model Result<FilteredOutputWorshipExtended>
@{
    ViewData["Title"] = "Последовательность ";
}
@*<div class="row col-sm-6"><breadcrumb></breadcrumb></div>*@
<div class="clearfix"></div>
@if (Model.Success)
{
    if (Model.Value.Name != null)
    {
        <div class="row">
            <h1 class="text-center @Model.Value.Name.Text.Language">@Model.Value.Name.Text.Text</h1>
        </div>
    }
    foreach (var s in Model.Value.Sections)
    {
        <div class="row">
            <div class="col-sm-2">
                @if (s.KindText != null)
                {
                    <label class="text-truncate red @s.KindText.Language">@s.KindText.Text</label>
                }
            </div>
            @{
                bool first = true;
                foreach (var para in s.Paragraphs)
                {
                    <div class="@(first ? "" : "col-sm-offset-2 ") col-sm-10 @GetStyle(para)">@para.Text.Text</div>
                    first = false;
                }
            }
        </div>
    }
}
else
{
    <div class="row col-sm-12"><h3>@Model.Error</h3></div>
}


@functions
{
public string GetStyle(FilteredParagraphNoted para)
{
    var str = para.Text.Language;
    if (para.Style.Header != HeaderCaption.NotDefined)
    {
        str += " " + para.Style.Header.ToString();
    }
    if (para.Style.IsBold)
    {
        str += " font-weight-bold";
    }
    if (para.Style.IsRed)
    {
        str += " red";
    }
    if (para.Style.IsItalic)
    {
        str += " font-italic";
    }

    return str;
}
}

TypiconOnline.Web/Views/Schedule/_EditDayPartial.cshtml
@model OutputDayEditModel

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Редактирование наименования богослужебного дня</h4>
    </div>
    <div class="modal-body">
        @if (Model == null)
        {
            <div class="row">
                <h4>Произошла ошибка доступа</h4>
            </div>
        }
        else
        {
            <form id="editOutputForm" asp-controller="Schedule" asp-action="EditDay" asp-route-id="@Model.Id">
                @{/*<div class="row">
                    <div class="col-sm-4"><input type="checkbox" asp-for="Name.IsBold" /> <b>Жирный</b></div>
                    <div class="col-sm-4"><input type="checkbox" asp-for="Name.IsItalic" /> <i>Курсивом</i></div>
                    <div class="col-sm-4"><input type="checkbox" asp-for="Name.IsRed" /> Красным</div>
                </div>*/}
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label asp-for="Name">Наименование:</label>
                    </div>
                    <div class="form-group col-sm-12">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col-sm-12">
                        <label>Печатный шаблон:</label>
                    </div>
                    <div class="form-group col-sm-12">
                        <select class="form-control" asp-for="PrintTemplateId" asp-items="@ViewBag.PrintTemplates">
                        </select>
                    </div>

                    <div class="col-xs-12"><button id="editDayBtn" class="btn btn-primary">Сохранить</button></div>
                </div>
            </form>
        }

    </div>
</div>

TypiconOnline.Web/Views/Schedule/_EditWorshipPartial.cshtml
@model OutputWorshipEditModel

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Редактирование наименования богослужебного дня</h4>
    </div>
    <div class="modal-body">
        @if (Model == null)
        {
            <div class="row">
                <h4>Произошла ошибка доступа</h4>
            </div>
        }
        else
        {
    <form id="editOutputForm" asp-controller="Schedule" asp-action="EditWorship" asp-route-id="@Model.Id">
        <div class="row">
            <div class="col-sm-12"><label asp-for="Time">Время богослужения</label></div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group input-group date" id="time">
                    <input type="text" class="form-control" asp-for="Time" />
                    <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12"><label asp-for="@Model.Name">Наименование</label></div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-4"><input type="checkbox" asp-for="NameStyle.IsBold" /> <b>Жирный</b></div>
                        <div class="col-sm-4"><input type="checkbox" asp-for="NameStyle.IsItalic" /> <i>Курсивом</i></div>
                        <div class="col-sm-4 red"><input type="checkbox" asp-for="NameStyle.IsRed" /> Красным</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-12">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12"><label asp-for="AdditionalName">Дополнительное наименование</label></div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-4"><input type="checkbox" asp-for="AdditionalNameStyle.IsBold" /> <b>Жирный</b></div>
                        <div class="col-sm-4"><input type="checkbox" asp-for="AdditionalNameStyle.IsItalic" /> <i>Курсивом</i></div>
                        <div class="col-sm-4 red"><input type="checkbox" asp-for="AdditionalNameStyle.IsRed" /> Красным</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-12">
                <input asp-for="AdditionalName" class="form-control" />
                <span asp-validation-for="AdditionalName" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12"><button id="editWorshipBtn" class="btn btn-primary">Сохранить</button></div>
        </div>
    </form>
        }

    </div>
</div>

TypiconOnline.Web/Views/Schedule/_View.cshtml
@using System.Linq;
@using TypiconOnline.Domain.Rules.Output;

@model Result<FilteredOutputWeek>

@if (Model.Success)
{
    <h2 class="@Model.Value.Name.Language">@Model.Value.Name.Text</h2>
    @foreach (var day in Model.Value.Days)
    {
        <h3>@day.Date.ToString("dd MMMM yyyy г.")</h3>
        if (day.Header != null)
        {
            <h3 class="@day.Header.Name.Language">@day.Header.Name</h3>
            <h4>Знак службы: @day.Header.SignName</h4>
        }

        <table>
            @{int i = 0;}
            @foreach (var worship in day.Worships)
            {
                <tr>
                    <td>@worship.Time&nbsp;</td>
                    <td>
                        @if (worship.HasSequence)
                        {
                            <a asp-controller="schedule" asp-action="sequence" asp-route-id="@ViewBag.Id" asp-route-worshipId="@worship.Id">
                                <span class="@worship.Name.Text.Language">@worship.Name.Text.Text</span>
                                @if (worship.AdditionalName != null)
                                {
                                    <span class="@worship.AdditionalName.Text.Language">@worship.AdditionalName.Text</span>
                                }
                            </a>
                        }
                        else
                        {
                            <span class="@worship.Name.Text.Language">@worship.Name.Text.Text</span>
                            @if (worship.AdditionalName != null)
                            {
                                <span class="@worship.AdditionalName.Text.Language">@worship.AdditionalName.Text</span>
                            }
                        }
                    </td>
                </tr>
                i++;
            }
        </table>
    }
}
else
{
    <h3>@Model.Error</h3>
}