TypiconOnline.Web/Controllers/SignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TypiconOnline.Domain.Command.Typicon;
using TypiconOnline.Domain.Identity;
using TypiconOnline.Domain.Query.Typicon;
using TypiconOnline.Domain.Typicon;
using TypiconOnline.Domain.WebQuery.Interfaces;
using TypiconOnline.Domain.WebQuery.Models;
using TypiconOnline.Domain.WebQuery.Typicon;
using TypiconOnline.Infrastructure.Common.Command;
using TypiconOnline.Infrastructure.Common.ErrorHandling;
using TypiconOnline.Infrastructure.Common.Query;
using TypiconOnline.Web.Extensions;
using TypiconOnline.Web.Services;
using TypiconOnline.WebServices.Authorization;

namespace TypiconOnline.Web.Controllers
{
    //[Authorize(Roles = RoleConstants.AdminAndEditorRoles)]
    public class SignController : TypiconChildBaseController<SignGridModel, Sign>
    {
        private const string DEFAULT_LANGUAGE = "cs-ru";

        public SignController(
            IQueryProcessor queryProcessor,
            ICommandProcessor commandProcessor,
            IAuthorizationService authorizationService) : base(queryProcessor, authorizationService, commandProcessor)
        {
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">SignId</param>
        /// <param name="fromSchedule">Признак того, что пришли из графика богослужений</param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Edit(int id, bool fromSchedule = false)
            => Perform(() => QueryProcessor.Process(new SignEditQuery(id)),
                        sign =>
                        {
                            ViewBag.Signs = QueryProcessor.GetSigns(sign.Value.TypiconId, DEFAULT_LANGUAGE, id);
                            ViewBag.PrintTemplates = QueryProcessor.GetPrintTemplates(sign.Value.TypiconId);

                            ViewBag.IsFromSchedule = fromSchedule;

                            return View(sign.Value);
                        });

        [HttpPost]
        public IActionResult Edit(SignCreateEditModel model)
            => Perform(() => CommandProcessor
                                    .Execute(new EditSignCommand(model.Id,
                                        model.Name,
                                        model.TemplateId,
                                        model.IsAddition,
                                        model.PrintTemplateId,
                                        model.Priority,
                                        model.RuleDefinition,
                                        model.ModRuleDefinition)),
                       () =>
                       {
                           return (ViewBag.IsFromSchedule is bool b == true)
                                ? RedirectToAction(nameof(ScheduleSettingsController.Index), "ScheduleSettings", new { id = model.TypiconId })
                                : RedirectToAction(nameof(Index), new { id = model.TypiconId });
                       });

        [HttpGet]
        public IActionResult Create(int id)
        {
            if (IsAuthorizedToEdit(id))
            {
                ViewBag.Signs = QueryProcessor.GetSigns(id, DEFAULT_LANGUAGE);
                ViewBag.PrintTemplates = QueryProcessor.GetPrintTemplates(id);

                return View(new SignCreateEditModel());
            }

            return Unauthorized();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SignCreateEditModel model)
        {
            if (ModelState.IsValid
                && IsAuthorizedToEdit(model.Id))
            {
                var command = new CreateSignCommand(model.Id,
                    model.Name,
                    model.TemplateId,
                    model.IsAddition,
                    model.PrintTemplateId,
                    model.Priority,
                    model.RuleDefinition,
                    model.ModRuleDefinition);

                await CommandProcessor.ExecuteAsync(command);

                return RedirectToAction(nameof(Index), new { id = model.Id });
            }

            ViewBag.Signs = QueryProcessor.GetSigns(model.Id, DEFAULT_LANGUAGE, model.Id);
            ViewBag.PrintTemplates = QueryProcessor.GetPrintTemplates(model.Id);

            return View(model);
        }

        #region Overrides
        protected override IGridQuery<SignGridModel> GetQuery(int id) => new AllSignsQuery(id, DEFAULT_LANGUAGE);

        protected override TypiconEntityByChildQuery<Sign> GetTypiconEntityByChildQuery(int id) 
            => new TypiconEntityBySignQuery(id);

        protected override DeleteRuleCommandBase<Sign> GetDeleteCommand(int id)
            =>  new DeleteSignCommand(id);

        #endregion
    }
}

TypiconOnline.Web/Controllers/TypiconController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypiconOnline.Infrastructure.Common.Query;
using TypiconOnline.Domain.WebQuery.Typicon;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using TypiconOnline.Domain.Identity;
using JqueryDataTables.ServerSide.AspNetCoreWeb;
using TypiconOnline.Domain.WebQuery.Models;
using TypiconOnline.Web.Extensions;
using TypiconOnline.Web.Models.TypiconViewModels;
using TypiconOnline.Domain.Command.Typicon;
using TypiconOnline.Infrastructure.Common.Command;
using TypiconOnline.AppServices.Interfaces;
using TypiconOnline.AppServices.Jobs;
using System.Linq.Expressions;
using TypiconOnline.Domain.WebQuery.Interfaces;
using TypiconOnline.Infrastructure.Common.ErrorHandling;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.IO;
using TypiconOnline.Domain.ItemTypes;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TypiconOnline.Web.Controllers
{
    [Authorize(Roles = RoleConstants.AdminAndEditorRoles)]
    public class TypiconController : TypiconBaseController<TypiconEntityFilteredModel>
    {
        private const string DEFAULT_LANGUAGE = "cs-ru";
        private readonly UserManager<User> _userManager;
        private readonly IJobRepository _jobs;
        private readonly ITypiconExportManager _exportManager;
        private readonly ITypiconImportManager _importManager;

        public TypiconController(
            ICommandProcessor commandProcessor
            , UserManager<User> userManager
            , IJobRepository jobs
            , IQueryProcessor queryProcessor
            , IAuthorizationService authorizationService
            , ITypiconExportManager exportManager
            , ITypiconImportManager importManager
            ) : base(queryProcessor, authorizationService, commandProcessor)
        {
            _userManager = userManager;
            _jobs = jobs;
            _exportManager = exportManager;
            _importManager = importManager;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            ClearStoredData(new AllTypiconsFilteredQuery(user.Id, DEFAULT_LANGUAGE));

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Typicons = QueryProcessor.GetPublicTypicons(withTemplates: true);

            return View(new CreateTypiconModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTypiconModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    throw new ApplicationException($"Невозможно найти Пользователя с Id = '{_userManager.GetUserId(User)}'.");
                }

                var command = new CreateTypiconCommand(model.Name, model.Description, model.SystemName, model.DefaultLanguage, model.TemplateId, user.Id);

                await CommandProcessor.ExecuteAsync(command);

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Typicons = QueryProcessor.GetPublicTypicons(withTemplates: true);

            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.AdministratorsRole)]
        public IActionResult Review(int id)
        {
            var model = QueryProcessor.Process(new TypiconClaimQuery(id));

            if (model.Failure)
            {
                return NotFound();
            }
            else
            {
                return View(model.Value);
            }
        }

        //[HttpPost]
        [Authorize(Roles = RoleConstants.AdministratorsRole)]
        //[ValidateAntiForgeryToken]
        //[Route("{id?}")]
        public IActionResult Approve(int id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            _jobs.Create(new ApproveTypiconClaimJob(id));

            return RedirectToAction("Index");
        }

        //[HttpPost]
        [Authorize(Roles = RoleConstants.AdministratorsRole)]
        //[ValidateAntiForgeryToken]
        //[Route("{id?}")]
        public async Task<IActionResult> Reject(TypiconClaimModel model)
        {
            if (ModelState.IsValid)
            {
                var command = new RejectTypiconClaimCommand(model.Id, model.ResultMessage);

                await CommandProcessor.ExecuteAsync(command);

                return RedirectToAction("Index");
            }

            return View(nameof(Review), model);
        }

        public async Task<IActionResult> LoadData()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
                }

                return LoadGridData(new AllTypiconsFilteredQuery(user.Id, DEFAULT_LANGUAGE));
            }
            catch (Exception e)
            {
                Console.Write(e.Message);
                return new JsonResult(new { error = "Internal Server Error" });
            }
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = GetModel(id);

            if (model.Failure)
            {
                return NotFound();
            }
            else
            {
                return View(model.Value);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TypiconEntityEditModel model)
        {
            if (ModelState.IsValid)
            {
                //проверить на права
                if (!IsAuthorizedToEdit(model.Id))
                {
                    return NotFound();
                }

                var command = new EditTypiconCommand(model.Id, model.Name, model.Description, model.IsTemplate, model.DefaultLanguage);

                await CommandProcessor.ExecuteAsync(command);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!IsTypiconsAuthor(id))
            {
                return Json(new { error = "Ошибка авторизации."});
            }

            var command = new DeleteTypiconCommand(id);

            var result = await CommandProcessor.ExecuteAsync(command);

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Удаление Заявки
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteClaim(int id)
        {
            var command = new DeleteTypiconClaimCommand(HttpContext.User, id);

            var result = await CommandProcessor.ExecuteAsync(command);

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Экспорт сериализованного Устава
        /// </summary>
        /// <param name="typiconVersionId"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = RoleConstants.AdministratorsRole)]
        public IActionResult ExportGet(int id)
        {
            var versions = QueryProcessor.Process(new TypiconVersionsQuery(id));

            if (versions.Success)
            {
                return PartialView("_ExportPartial", versions.Value.Select(c => new SelectListItem() { Text = c.Name, Value = c.Id.ToString() }));
            }

            return NotFound();
        }

        /// <summary>
        /// Экспорт сериализованного Устава
        /// </summary>
        /// <param name="typiconVersionId"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = RoleConstants.AdministratorsRole)]
        public IActionResult Export(int versionId)
        {
            var exportResult = _exportManager.Export(versionId);

            if (exportResult.Success)
            {
                return Json(new { file = exportResult.Value.Content, type = exportResult.Value.ContentType, filename = exportResult.Value.FileDownloadName });
            }
            else
            {
                return new JsonResult(new { error = exportResult.Error });
            }
        }

        /// <summary>
        /// Экспорт сериализованного Устава
        /// </summary>
        /// <param name="typiconVersionId"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = RoleConstants.AdministratorsRole)]
        public IActionResult Import(IFormFile file)
        {
            if (file != null)
            {
                byte[] data = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(file.OpenReadStream()))
                {
                    data = binaryReader.ReadBytes((int)file.Length);
                }

                var importResult = _importManager.Import(data);

                return new JsonResult(new { success = importResult.Success, msg = importResult.Error });
            }
            
            return new JsonResult(new { success = false, msg = "Ошибка: пустой файл" });
        }

        [HttpGet]
        public IActionResult Operations(int id) => Edit(id);

        [HttpGet]
        public IActionResult Editors(int id) => Edit(id);

        //[HttpPost]

TypiconOnline.Web/Views/Shared/Components/TypiconTab/Default.cshtml
@using TypiconOnline.Web.Models.TypiconViewModels
@model TypiconTabModel
    
    <div class="row">
        <div class="col-12">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="index">Главная</a></li>
                <li><a asp-controller="Typicon" asp-action="index">Уставы</a></li>
                @switch (Model.Tab)
                {
                    case TypiconTab.Properties:
                    case TypiconTab.Operations:
                    case TypiconTab.ScheduleSettings:
                    case TypiconTab.Editors:
                    case TypiconTab.PrintTemplate:
                    case TypiconTab.Variables:
                    case TypiconTab.Sign:
                    case TypiconTab.Menology:
                    case TypiconTab.Triodion:
                    case TypiconTab.Common:
                    case TypiconTab.Explicit:
                    case TypiconTab.Kathizma:
                        <text>
                            <li class="active">Устав</li>
                        </text>
                        break;
                    case TypiconTab.CreatePrintTemplate:
                    case TypiconTab.EditPrintTemplate:
                        <text>
                            <li><a asp-controller="PrintTemplate" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Печатный шаблон</li>
                        </text>
                        break;
                    case TypiconTab.CreateSign:
                    case TypiconTab.EditSign:
                        <text>
                            <li><a asp-controller="Sign" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Знак службы</li>
                        </text>
                        break;
                    case TypiconTab.CreateMenology:
                    case TypiconTab.EditMenology:
                        <text>
                            <li><a asp-controller="MenologyRule" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Минея</li>
                        </text>
                        break;
                    case TypiconTab.CreateTriodion:
                    case TypiconTab.EditTriodion:
                        <text>
                            <li><a asp-controller="TriodionRule" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Триодь</li>
                        </text>
                        break;
                    case TypiconTab.CreateCommon:
                    case TypiconTab.EditCommon:
                        <text>
                            <li><a asp-controller="CommonRule" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Общее правило</li>
                        </text>
                        break;
                    case TypiconTab.CreateExplicit:
                    case TypiconTab.EditExplicit:
                        <text>
                            <li><a asp-controller="ExplicitAddRule" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Явное правило</li>
                        </text>
                        break;
                    case TypiconTab.EditVariable:
                        <text>
                            <li><a asp-controller="TypiconVariables" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                            <li class="active">Переменная Устава</li>
                        </text>
                        break;
                        @*case TypiconTab.EditKathizma:
                <text>
                    <li><a asp-controller="Kathizma" asp-action="index" asp-route-id="@Model.TypiconId">Устав</a></li>
                    <li class="active">Кафизма</li>
                </text>
                break;*@
                }
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h1>Устав - @Model.Name</h1>
        </div>
    </div>
    <div class="row">
        <ul class="nav nav-tabs">
            @if (Model.Tab == TypiconTab.Properties)
            {
                <li class="active"><a href="#">Свойства</a></li>
            }
            else
            {
                <li><a asp-controller="Typicon" asp-action="Edit" asp-route-id="@Model.TypiconId">Свойства</a></li>
            }
            @if (Model.Tab == TypiconTab.ScheduleSettings)
            {
                <li class="active"><a href="#">График богослужений</a></li>
            }
            else
            {
                <li><a asp-controller="ScheduleSettings" asp-action="Index" asp-route-id="@Model.TypiconId">График богослужений</a></li>
            }
            @if (Model.Tab == TypiconTab.Variables)
            {
                <li class="active">
                    <a href="#">
                        Переменные
                        @if (!Model.IsTemplate && Model.VariablesCount > 0)
                        {
                            <span id="varCountSpan" class="label label-danger"
                                  title="Количество переменных без определения">@Model.VariablesCount</span>
                            }
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a asp-controller="TypiconVariables" asp-action="Index" asp-route-id="@Model.TypiconId">
                        Переменные
                        @if (!Model.IsTemplate && Model.VariablesCount > 0)
                        {
                            <span id="varCountSpan" class="label label-danger"
                                  title="Количество переменных без определения">@Model.VariablesCount</span>
                            }
                    </a>
                </li>
            }
            @if (Model.Tab == TypiconTab.Operations)
            {
                <li class="active"><a href="#">Операции @((!Model.IsModified) ? "<span id=\"varCountSpan\" class=\"label label-warning\" title=\"Есть неопубликованные изменения в Уставе\">*</span>" : "")</a></li>
            }
            else
            {
                <li><a asp-controller="Typicon" asp-action="Operations" asp-route-id="@Model.TypiconId">Операции</a></li>
            }
            @if (Model.UserIsAuthor)
            {
                @if (Model.Tab == TypiconTab.Editors)
                {
                    <li class="active"><a href="#">Редакторы</a></li>
                }
                else
                {
                    <li><a asp-controller="Typicon" asp-action="Editors" asp-route-id="@Model.TypiconId">Редакторы</a></li>
                }
            }
            @if (Model.Tab == TypiconTab.PrintTemplate)
            {
                <li class="active">
                    <a href="#">
                        Печатные шаблоны
                        @if (Model.EmptyPrintTemplatesCount > 0)
                        {
                            <span id="varCountSpan" class="label label-@((!Model.IsTemplate && Model.EmptyPrintTemplatesCount > 0) ? "danger" : "default")"
                                  title="Количество печатных шаблонов без загруженных файлов">@Model.EmptyPrintTemplatesCount</span>
                            }
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a asp-controller="PrintTemplate" asp-action="Index" asp-route-id="@Model.TypiconId">
                        Печатные шаблоны
                        @if (Model.EmptyPrintTemplatesCount > 0)
                        {
                            <span id="varCountSpan" class="label label-@((!Model.IsTemplate && Model.EmptyPrintTemplatesCount > 0) ? "danger" : "default")"
                                  title="Количество печатных шаблонов без загруженных файлов">@Model.EmptyPrintTemplatesCount</span>
                            }
                    </a>
                </li>
            }
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    Правила
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    @if (Model.Tab == TypiconTab.Sign)
                    {
                        <li class="active"><a href="#">Знаки служб</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Sign" asp-action="Index" asp-route-id="@Model.TypiconId">Знаки служб</a></li>
                    }
                    @if (Model.Tab == TypiconTab.Menology)
                    {
                        <li class="active"><a href="#">Минея</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="MenologyRule" asp-action="Index" asp-route-id="@Model.TypiconId">Минея</a></li>
                    }
                    @if (Model.Tab == TypiconTab.Triodion)
                    {
                        <li class="active"><a href="#">Триодь</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="TriodionRule" asp-action="Index" asp-route-id="@Model.TypiconId">Триодь</a></li>
                    }
                    @if (Model.Tab == TypiconTab.Common)
                    {
                        <li class="active"><a href="#">Общие</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="CommonRule" asp-action="Index" asp-route-id="@Model.TypiconId">Общие</a></li>
                    }
                    @if (Model.Tab == TypiconTab.Explicit)
                    {
                        <li class="active"><a href="#">Явные</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="ExplicitAddRule" asp-action="Index" asp-route-id="@Model.TypiconId">Явные</a></li>
                    }
                    @*@if (Model.Tab == TypiconTab.Kathizma)
                {
                    <li class="active"><a href="#">Кафизмы</a></li>
                }
                else
                {
                    <li><a asp-controller="Kathisma" asp-action="Index" asp-route-id="@Model.TypiconId">Кафизмы</a></li>
                }*@
                </ul>
            </li>
        </ul>
    </div>