TypiconOnline.Web/Controllers/MenologyDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TypiconOnline.Domain.Command.Books;
using TypiconOnline.Domain.Identity;
using TypiconOnline.Domain.ItemTypes;
using TypiconOnline.Domain.WebQuery.Books;
using TypiconOnline.Domain.WebQuery.Interfaces;
using TypiconOnline.Domain.WebQuery.Models;
using TypiconOnline.Infrastructure.Common.Command;
using TypiconOnline.Infrastructure.Common.Query;

namespace TypiconOnline.Web.Controllers
{
    [Authorize(Roles = RoleConstants.AdminAndTypesetterRoles)]
    public class MenologyDayController : TextBaseController<MenologyDayGridModel>
    {
        public MenologyDayController(IQueryProcessor queryProcessor
            , ICommandProcessor commandProcessor) : base(queryProcessor, commandProcessor)
        {
        }


        // GET: MenologyDay/Edit/5
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">MenologyRuleId</param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }

            var found = QueryProcessor.Process(new MenologyDayEditQuery(id));

            if (found.Success)
            {
                return View(found.Value);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MenologyDayEditModel model)
        {
            if (ModelState.IsValid)
            {
                var command = new EditMenologyDayCommand(model.Id,
                    model.LeapDate,
                    model.Name,
                    model.ShortName,
                    model.IsCelebrating,
                    model.UseFullName,
                    model.Definition);

                await CommandProcessor.ExecuteAsync(command);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new MenologyDayEditModel()
            {
                //Name = new ItemTextStyled(new ItemText(new ItemTextUnit("cs-ru", "[Новое значение]"))),
                //ShortName = new ItemText(new ItemTextUnit("cs-ru", "[Новое значение]"))
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(MenologyDayEditModel model)
        {
            if (ModelState.IsValid)
            {
                var command = new CreateMenologyDayCommand(model.LeapDate,
                    model.Name,
                    model.ShortName,
                    model.IsCelebrating,
                    model.UseFullName,
                    model.Definition);

                await CommandProcessor.ExecuteAsync(command);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpPost]
        [Route("[controller]/[action]/{worshipId}")]
        public async Task<IActionResult> Delete(int worshipId)
        {
            try
            {
                //удаление
                var result = await CommandProcessor.ExecuteAsync(new DeleteMenologyDayCommand(worshipId));

                ClearStoredData(GetQuery());

                return Json(data: result.Success);
            }
            catch (Exception)
            {
                throw;
            }
        }

        protected override IGridQuery<MenologyDayGridModel> GetQuery() => new AllMenologyDaysQuery(DEFAULT_LANGUAGE);
    }
}

TypiconOnline.Web/Views/MenologyDay/Create.cshtml
@model MenologyDayEditModel
@{
    ViewData["Title"] = "Создание Текста Минейной службы";
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="index">Главная</a></li>
                <li><a asp-controller="MenologyDay" asp-action="index">Тексты минейных служб</a></li>
                <li class="active">Создание Текста Минейной службы</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h2>@ViewData["Title"]</h2>
        </div>
    </div>
    <div class="row">
        <form class="row" asp-action="Create" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <div class="col-sm-8">
                    <label asp-for="Name">Наименование:</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="form-group">
                <div class="col-sm-8">
                    <label asp-for="ShortName">Краткое наименование:</label>
                    <input asp-for="ShortName" class="form-control" />
                    <span asp-validation-for="ShortName" class="text-danger"></span>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="form-group">
                <div class="col-sm-8">
                    <label asp-for="LeapDate">Дата (високосный год):</label>
                    <div class="input-group date" id="leapdate">
                        <input type="text" class="form-control" />
                        <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
                    </div>
                    <input type="hidden" id="dtp_leapdate" value="@Model.LeapDate?.ToString("yyyy-MM-dd")" name="LeapDate" />
                    <span asp-validation-for="LeapDate" class="text-danger"></span>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="checkbox col-sm-8">
                <label>
                    <input type="checkbox" asp-for="IsCelebrating" /> <b>Признак Господского или Богородичного праздника, его предпразднества или попразднества</b>
                </label>
            </div>
            <div class="clearfix"></div>
            <div class="checkbox col-sm-8">
                <label>
                    <input type="checkbox" asp-for="UseFullName" /> <b>Признак, использовать ли полное имя при составлении расписания. Например, имеет значение true для праздника Недели по Рождестве</b>
                </label>
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-12">
                <label asp-for="Definition">Определение текста службы:</label>
                <div>
                    <textarea id="definition" class="form-control rounded-0" rows="30" asp-for="Definition"></textarea>
                    <span asp-validation-for="Definition" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group"><div class="validation" asp-validation-summary="ModelOnly"></div></div>
            <div class="col-xs-12"><button class="btn btn-primary" asp-action="Create">Создать</button></div>
        </form>
    </div>
</div>
</div>
@section Scripts
    {
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="~/css/itemtext.css" />

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" />

    <script src="~/lib/codemirror/codemirror.js"></script>
    <link rel="stylesheet" href="~/lib/codemirror/codemirror.css">
    <link rel="stylesheet" href="~/lib/codemirror/show-hint.css">
    <link rel="stylesheet" href="~/lib/codemirror/xq-light.css">
    <script src="~/lib/codemirror/xml.js"></script>
    <script src="~/lib/codemirror/show-hint.js"></script>
    <script src="~/lib/codemirror/xml-hint.js"></script>
    <script src="~/js/textarea.js"></script>

    <script src="~/lib/momentjs/moment-with-locales.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datetimepicker.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            createTextArea("definition", '@Model.Definition');

            $('#leapdate').datetimepicker({
                locale: 'ru',
                dayViewHeaderFormat: "MMMM",
                format: "DD MMMM",
                viewMode: "days",
                maxDate: "2016-12-31",
                minDate: "2016-01-01",
                useCurrent: false,
                showClear: true
                @if (Model.LeapDate != null)
                {
                    <text>, defaultDate: "@Model.LeapDate?.ToString("yyyy-MM-dd")"</text>
                }
            })
            .on('dp.change', function (e) {
                if (!e.date) {
                    $('#dtp_leapdate').attr("value", "");
                }
                else {
                    $('#dtp_leapdate').attr("value", moment(e.date).format("YYYY-MM-DD"));
                }
            })
            @if (Model.LeapDate == null)
            {
                <text>.on('dp.show', function() {
                    return $(this).data('DateTimePicker').defaultDate(moment("2016-01-01"));
                })</text>
            };
        });

    </script>

    @await Html.PartialAsync("_ValidationScriptsPartial")
}

TypiconOnline.Web/Views/MenologyDay/Edit.cshtml
@model MenologyDayEditModel
@{
    ViewData["Title"] = "Редактирование Текста Минейной службы";
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="index">Главная</a></li>
                <li><a asp-controller="MenologyDay" asp-action="index">Тексты минейных служб</a></li>
                <li class="active">Редактирование Текста Минейной службы</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h2>@ViewData["Title"]</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form class="row" asp-action="Edit" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-sm-8">
                        <label asp-for="Name">Наименование:</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    <div class="col-sm-8">
                        <label asp-for="ShortName">Краткое наименование:</label>
                        <input asp-for="ShortName" class="form-control" />
                        <span asp-validation-for="ShortName" class="text-danger"></span>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    <div class="col-sm-8">
                        <label asp-for="LeapDate">Дата (високосный год):</label>
                        <div class="input-group date" id="leapdate">
                            <input type="text" class="form-control" />
                            <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
                        </div>
                        <input type="hidden" id="dtp_leapdate" value="@Model.LeapDate?.ToString("yyyy-MM-dd")" name="LeapDate" />
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="checkbox col-sm-8">
                    <label>
                        <input type="checkbox" asp-for="IsCelebrating" /> <b>Признак Господского или Богородичного праздника, его предпразднества или попразднества</b>
                    </label>
                </div>
                <div class="clearfix"></div>
                <div class="checkbox col-sm-8">
                    <label>
                        <input type="checkbox" asp-for="UseFullName" /> <b>Признак, использовать ли полное имя при составлении расписания. Например, имеет значение true для праздника Недели по Рождестве</b>
                    </label>
                </div>
                <div class="clearfix"></div>
                <div class="form-group col-xs-12">
                    <label asp-for="Definition">Определение текста службы:</label>
                    <div>
                        <textarea id="definition" class="form-control rounded-0" rows="30" asp-for="Definition"></textarea>
                        <span asp-validation-for="Definition" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group"><div class="validation" asp-validation-summary="ModelOnly"></div></div>
                <div class="col-xs-12"><button class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Сохранить</button></div>
            </form>
        </div>
    </div>
</div>
@section Scripts
    {
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="~/css/itemtext.css" />

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" />

    <script src="~/lib/codemirror/codemirror.js"></script>
    <link rel="stylesheet" href="~/lib/codemirror/codemirror.css">
    <link rel="stylesheet" href="~/lib/codemirror/show-hint.css">
    <link rel="stylesheet" href="~/lib/codemirror/xq-light.css">
    <script src="~/lib/codemirror/xml.js"></script>
    <script src="~/lib/codemirror/show-hint.js"></script>
    <script src="~/lib/codemirror/xml-hint.js"></script>
    <script src="~/js/textarea.js"></script>

    <script src="~/lib/momentjs/moment-with-locales.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datetimepicker.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            createTextArea("definition", '@Model.Definition');

            $('#leapdate').datetimepicker({
                locale: 'ru',
                dayViewHeaderFormat: "MMMM",
                format: "DD MMMM",
                viewMode: "days",
                maxDate: "2016-12-31",
                minDate: "2016-01-01",
                useCurrent: false,
                showClear: true
                @if (Model.LeapDate != null)
                {
                    <text>, defaultDate: "@Model.LeapDate?.ToString("yyyy-MM-dd")"</text>
                }
            })
            .on('dp.change', function (e) {
                if (!e.date) {
                    $('#dtp_leapdate').attr("value", "");
                }
                else {
                    $('#dtp_leapdate').attr("value", moment(e.date).format("YYYY-MM-DD"));
                }
            })
            @if (Model.LeapDate == null)
            {
                <text>.on('dp.show', function() {
                    return $(this).data('DateTimePicker').defaultDate(moment("2016-01-01"));
                })</text>
            };
        });

    </script>

    @await Html.PartialAsync("_ValidationScriptsPartial")
}

TypiconOnline.Web/Views/MenologyDay/Index.cshtml
<link href="~/css/datatables.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/responsive.bootstrap.min.css" rel="stylesheet" />

@{
    ViewData["Title"] = "Тексты минейных служб";
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="index">Главная</a></li>
                <li class="active">Минея</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12"><h1>@ViewData["Title"]</h1></div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <a class="btn btn-info" href="/MenologyDay/Create"><i class="fa fa-plus"></i> Новая служба Минеи</a>
        </div>
        <div class="form-group col-12">
            <div class="justify-content-center align-content-center">
                <table id="mdGrid" class="table table-striped table-bordered" style="width:100%">
                    <thead class="text-center">
                        <tr>
                            <th>Id</th>
                            <th>Дата</th>
                            <th>Дата (вис. год)</th>
                            <th>Наименование</th>
                            <th>Краткое наим.</th>
                            <th>Праздник</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {




    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#mdGrid").DataTable(
                {
                    "processing": true, // for show progress bar
                    "serverSide": true, // for process server side
                    "filter": true, // this is for disable filter (search box)
                    "orderMulti": false, // for disable multiple column at once
                    "language": {
                        "url": "/lib/datatables/russian.json"
                    },
                    "ajax": {
                        "url": "/MenologyDay/LoadData",
                        "type": "POST",
                        "datatype": "json"
                    },
                    "columnDefs":
                        [{
                            "targets": [0],
                            "visible": false,
                            "searchable": false
                        }],
                    "columns": [
                        { "data": "Id", "name": "Id", "autoWidth": true },
                        { "data": "Date", "name": "Date", "autoWidth": true },
                        { "data": "LeapDate", "name": "LeapDate", "autoWidth": true },
                        { "data": "Name", "name": "Name", "autoWidth": true },
                        { "data": "ShortName", "name": "ShortName", "autoWidth": true },
                        { "data": "IsCelebrating", "name": "IsCelebrating", "autoWidth": true },
                        {
                            data: null, render: function (data, type, row) {
                                return '<a class="btn btn-primary" href="/MenologyDay/Edit/' + row.Id + '">Редактировать</a> <a href="#" class="btn btn-danger btn-delete">Удалить</a>';
                            },
                            orderable: false
                        },
                    ]
                }
            );
        });


        $('#mdGrid').on('click', 'tbody tr td .btn-delete', function () {
            var table = $('#mdGrid').DataTable();
            var row = table.row($(this).parents('tr'));
            var data = row.data();
            if (confirm('Вы действительно хотите удалить Службу Минеи "' + data.Name + '"?')) {

                $.post("/MenologyDay/Delete/" + data.Id, function (result) {
                    if (result) {
                        row.remove();
                    }
                    else {
                        alert("Что-то пошло не так.");
                    }
                    table.draw(false);
                });
            }
            else {
                return false;
            }
        });
    </script>
}