TypiconOnline.Web/Controllers/ScheduleSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TypiconOnline.Domain.Identity;
using TypiconOnline.Domain.WebQuery.Typicon;
using TypiconOnline.Infrastructure.Common.Command;
using TypiconOnline.Infrastructure.Common.ErrorHandling;
using TypiconOnline.Infrastructure.Common.Query;
using TypiconOnline.Domain.WebQuery.Models;
using TypiconOnline.Domain.Command.Typicon;
using TypiconOnline.Web.Services;
using TypiconOnline.Domain.WebQuery.Grid;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TypiconOnline.Web.Controllers
{
    [Authorize(Roles = RoleConstants.AdminAndEditorRoles)]
    public class ScheduleSettingsController : BaseController
    {
        private readonly GridStore<SignGridModel> signStore;
        private readonly GridStore<MenologyRuleGridModel> menologyStore;
        private readonly GridStore<TriodionRuleGridModel> triodionStore;
        private readonly GridStore<DateGridItem> includedStore;

        public ScheduleSettingsController(
            IQueryProcessor queryProcessor,
            ICommandProcessor commandProcessor)
            : base(queryProcessor, commandProcessor)
        {
            signStore = new GridStore<SignGridModel>(queryProcessor
                , commandProcessor
                , this);

            menologyStore = new GridStore<MenologyRuleGridModel>(queryProcessor
                , commandProcessor
                , this
                //храним в сессии
                , storeToSession: false );

            triodionStore = new GridStore<TriodionRuleGridModel>(queryProcessor
                , commandProcessor
                , this
                //храним в сессии
                , storeToSession: false);

            includedStore = new GridStore<DateGridItem>(queryProcessor
                , commandProcessor
                , this);
        }

        // GET: /<controller>/
        public IActionResult Index(int id)
            => Perform(() => QueryProcessor.Process(new ScheduleWeekSettingsQuery(id)),
                       c => View(c.Value));

        [HttpGet]
        public IActionResult EditDays(int id)
            => Perform(() => QueryProcessor.Process(new ScheduleWeekSettingsQuery(id)),
                       c => PartialView("_EditDaysPartial", c.Value));

        [HttpPost]
        public IActionResult EditDays(ScheduleSettingsWeekDaysModel model)
            => Perform(() => CommandProcessor.Execute(new ScheduleSettingsWeekDaysCommand(model.TypiconId)
                                {
                                    IsMonday = model.IsMonday,
                                    IsTuesday = model.IsTuesday,
                                    IsWednesday = model.IsWednesday,
                                    IsThursday = model.IsThursday,
                                    IsFriday = model.IsFriday,
                                    IsSaturday = model.IsSaturday,
                                    IsSunday = model.IsSunday
                                }),
                       () => PartialView("_ViewDaysPartial", model));

        #region Sign

        public IActionResult LoadSigns(int id) => signStore.LoadGridData(new AllScheduleSignsQuery(id));

        /// <summary>
        /// загружаем таблицу знаков службы для добавления
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult LoadAddSignGrid(int id) => signStore.LoadGridData(new AllScheduleSignsToLoadQuery(id));

        [HttpGet]
        [Route("[controller]/[action]/{typiconId}")]
        public IActionResult AddSign(int typiconId)
            => Perform(() => QueryProcessor.Process(new ScheduleWeekSettingsQuery(typiconId)),
                       () => PartialView("_AddSignPartial"));

        [HttpPost]
        [Route("[controller]/[action]/{typiconId}/{ruleId}")]
        public IActionResult AddSign(int typiconId, int ruleId)
            => Perform(() => CommandProcessor.Execute(new AddScheduleSignCommand(typiconId, ruleId)),
                       () => Accepted());

        [HttpPost]
        [Route("[controller]/[action]/{ruleId}")]
        public IActionResult DeleteSign(int ruleId)
            => Perform(() => CommandProcessor.Execute(new DeleteScheduleSignCommand(ruleId)),
                       () => Accepted());

        #endregion

        #region MenologyRule

        public IActionResult LoadMenology(int id) => menologyStore.LoadGridData(new AllScheduleMenologyQuery(id));

        /// <summary>
        /// загружаем таблицу знаков службы для добавления
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("[controller]/[action]/{id}/{date?}")]
        public IActionResult LoadMenologyToAddGrid(int id, DateTime? date) => menologyStore.LoadGridData(new AllScheduleMenologyToAddQuery(id, date));

        [HttpGet]
        [Route("[controller]/[action]/{typiconId}")]
        public IActionResult AddMenology(int typiconId)
            => Perform(() => QueryProcessor.Process(new ScheduleWeekSettingsQuery(typiconId)),
                       () => PartialView("_AddMenologyPartial"));

        [HttpPost]
        [Route("[controller]/[action]/{typiconId}/{ruleId}")]
        public IActionResult AddMenology(int typiconId, int ruleId)
            => Perform(() => CommandProcessor.Execute(new AddScheduleMenologyCommand(typiconId, ruleId)),
                       () => Accepted());

        [HttpPost]
        [Route("[controller]/[action]/{ruleId}")]
        public IActionResult DeleteMenology(int ruleId)
            => Perform(() => CommandProcessor.Execute(new DeleteScheduleMenologyCommand(ruleId)),
                       () => Accepted());

        #endregion

        #region TriodionRule

        public IActionResult LoadTriodion(int id) => triodionStore.LoadGridData(new AllScheduleTriodionQuery(id));

        /// <summary>
        /// загружаем таблицу для добавления
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("[controller]/[action]/{id}/{days?}")]
        public IActionResult LoadTriodionToAddGrid(int id, int? days) => triodionStore.LoadGridData(new AllScheduleTriodionToAddQuery(id, days));

        [HttpGet]
        [Route("[controller]/[action]/{typiconId}")]
        public IActionResult AddTriodion(int typiconId)
            => Perform(() => QueryProcessor.Process(new ScheduleWeekSettingsQuery(typiconId)),
                       () => PartialView("_AddTriodionPartial"));

        [HttpPost]
        [Route("[controller]/[action]/{typiconId}/{ruleId}")]
        public IActionResult AddTriodion(int typiconId, int ruleId)
            => Perform(() => CommandProcessor.Execute(new AddScheduleTriodionCommand(typiconId, ruleId)),
                       () => Accepted());

        [HttpPost]
        [Route("[controller]/[action]/{ruleId}")]
        public IActionResult DeleteTriodion(int ruleId)
            => Perform(() => CommandProcessor.Execute(new DeleteScheduleTriodionCommand(ruleId)),
                       () => Accepted());

        #endregion

        //#region IncludedDates

        //public IActionResult LoadIncludedDates(int id) => includedStore.LoadGridData(new AllScheduleIncludedDatesQuery(id));

        /////// <summary>
        /////// загружаем таблицу для добавления
        /////// </summary>
        /////// <param name="id"></param>
        /////// <returns></returns>
        ////[Route("[controller]/[action]/{id}/{days?}")]
        ////public IActionResult LoadTriodionToAddGrid(int id, int? days) => triodionStore.LoadGridData(new AllScheduleTriodionToAddQuery(id, days));

        //[HttpGet]
        //[Route("[controller]/[action]/{typiconId}")]
        //public IActionResult ShowIncludedDateToAdd(int typiconId)
        //    => Perform(() => QueryProcessor.Process(new ScheduleIncludedDatesQuery(typiconId)),
        //               () => PartialView("_AddTriodionPartial"));

        //[HttpPost]
        //[Route("[controller]/[action]/{typiconId}/{date}")]
        //public IActionResult AddIncludedDate(int typiconId, DateTime date)
        //    => Perform(() => CommandProcessor.Execute(new AddScheduleIncludedDateCommand(typiconId, date)),
        //               () => Accepted());

        //[HttpPost]
        //[Route("[controller]/[action]/{date}")]
        //public IActionResult DeleteIncludedDate(int typiconId, DateTime date)
        //    => Perform(() => CommandProcessor.Execute(new DeleteScheduleIncludedDateCommand(typiconId, date)),
        //               () => Accepted());

        //#endregion

        
    }
}

TypiconOnline.Web/Views/ScheduleSettings/Index.cshtml
@model ScheduleSettingsWeekDaysModel
@{
    ViewData["Title"] = "График богослужений";
}
<div class="container">
    @await Component.InvokeAsync("TypiconTab", new { typiconId = ViewContext.RouteData.Values["id"], tab = TypiconTab.ScheduleSettings })
    <div class="row">
        <div class="col-12"><h1>@ViewData["Title"]</h1></div>
    </div>
    <div class="row">
        <div class="col-12"><h3>Дни недели</h3> <p><button id="editDays" class="btn btn-primary" data-id="@ViewContext.RouteData.Values["id"]">Редактировать</button></div></p>
    </div>
    <div class="row">
        <div id="daysContainer" class="col-sm-12 col-md-6 col-lg-4">@await Html.PartialAsync("_ViewDaysPartial", Model)</div>
    </div>
    <div class="row">
        <div class="col-12"><h3>Знаки служб</h3> </p><button id="addSign" class="btn btn-primary" data-id="@ViewContext.RouteData.Values["id"]">Добавить Знак службы</button></p></div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <div class="justify-content-center align-content-center">
                <table id="signGrid" class="table table-striped table-bordered" style="width:100%">
                    <thead class="text-center">
                        <tr>
                            <th>Id</th>
                            <th>Наименование</th>
                            <th>Шаблон</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12"><h3>Минея</h3> </p><button id="addMenology" class="btn btn-primary" data-id="@ViewContext.RouteData.Values["id"]">Добавить Минею</button></p></div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <div class="justify-content-center align-content-center">
                <table id="menologyGrid" class="table table-striped table-bordered" style="width:100%">
                    <thead class="text-center">
                        <tr>
                            <th>Id</th>
                            <th>Наименование</th>
                            <th>Знак службы</th>
                            <th>Дата</th>
                            <th>Дата (вис. год)</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12"><h3>Триодь</h3> </p><button id="addTriodion" class="btn btn-primary" data-id="@ViewContext.RouteData.Values["id"]">Добавить Триодь</button></p></div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <div class="justify-content-center align-content-center">
                <table id="triodionGrid" class="table table-striped table-bordered" style="width:100%">
                    <thead class="text-center">
                        <tr>
                            <th>Id</th>
                            <th>Наименование</th>
                            <th>Знак службы</th>
                            <th>Дней от Пасхи</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    @*<div class="row">
            <div class="col-12"><h3>Включенные даты</h3></div>
        </div>
        <div class="row">
            <div class="col-12">
                <label>Добавить Включенную дату</label>
                <div class="input-group date" id="addInclude">
                    <input type="text" class="form-control">
                    <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
                </div>
                <input type="hidden" id="addInclude_date" value=""/>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-12">
                <div class="justify-content-center align-content-center">
                    <table id="includeGrid" class="table table-striped table-bordered" style="width:100%">
                        <thead class="text-center">
                            <tr>
                                <th>Дата</th>
                                <th>Действия</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>*@
</div>

<div class="modal fade edit-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div id="modalWindow" class="modal-dialog modal-lg">
    </div>
</div>
@*<div class="modal fade edit-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div id="modalDatesWindow" class="modal-dialog modal-sm">

        </div>
    </div>*@


@section Scripts {
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/itemtext.css"/>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>    
    <script src="~/js/schedulesettings.js"></script>

    <script src="~/lib/momentjs/moment-with-locales.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datetimepicker.min.js"></script>

    @*<script>
            var includedDates = @Html.Raw(Json.Serialize(Model.IncludedDates));
            var excludedDates = @Html.Raw(Json.Serialize(Model.ExcludedDates));
        </script>*@

    @await Html.PartialAsync("_ValidationScriptsPartial")
}

TypiconOnline.Web/Views/ScheduleSettings/_AddMenologyPartial.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Добавить службу Минеи</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="form-group col-sm-12 col-md-4">
                <div id="datepicker"></div>
                <button id="btnNoDate" type="button" class="btn btn-primary" aria-pressed="true">Переходящие праздники</button>
            </div>
        </div>
        
        <div class="row">
            <div class="form-group col-sm-12">
                <div class="justify-content-center align-content-center">
                    <table id="addMenologyGrid" class="table table-striped table-bordered" style="width:100%">
                        <thead class="text-center">
                            <tr>
                                <th>Id</th>
                                <th>Наименование</th>
                                <th>Знак службы</th>
                                <th>Дата</th>
                                <th>Дата (вис.год)</th>
                                <th>Действия</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

TypiconOnline.Web/Views/ScheduleSettings/_AddSignPartial.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Добавить Знак службы</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="form-group col-sm-12">
                <div class="justify-content-center align-content-center">
                    <table id="addSignGrid" class="table table-striped table-bordered" style="width:100%">
                        <thead class="text-center">
                            <tr>
                                <th>Id</th>
                                <th>Наименование</th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

TypiconOnline.Web/Views/ScheduleSettings/_AddTriodionPartial.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Добавить службу Триоди</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="form-group col-sm-12 col-md-4">
                <label>Количество дней от Пасхи:</label>
                <input type="number" id="daysFE" class="form-control" placeholder="Количество дней от Пасхи" value="0"/>
                <button id="btnAllDays" type="button" class="btn btn-primary" aria-pressed="true">Показать все праздники</button>
            </div>
        </div>
        
        <div class="row">
            <div class="form-group col-sm-12">
                <div class="justify-content-center align-content-center">
                    <table id="addTriodionGrid" class="table table-striped table-bordered" style="width:100%">
                        <thead class="text-center">
                            <tr>
                                <th>Id</th>
                                <th>Наименование</th>
                                <th>Знак службы</th>
                                <th>Дней от Пасхи</th>
                                <th>Действия</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

TypiconOnline.Web/Views/ScheduleSettings/_EditDaysPartial.cshtml
@model ScheduleSettingsWeekDaysModel

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Редактирование графика дней богослужений</h4>
    </div>
    <div class="modal-body">
        @if (Model == null)
        {
            <div class="row">
                <h4>Произошла ошибка доступа</h4>
            </div>
        }
        else
        {
            <form id="editDaysForm" asp-controller="ScheduleSettings" asp-action="EditDays" asp-route-TypiconId="@Model.TypiconId">
                <div class="row">
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsMonday" /> Понедельник
                    </div>
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsTuesday" /> Вторник
                    </div>
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsWednesday" /> Среда
                    </div>
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsThursday" /> Четверг
                    </div>
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsFriday" /> Пятница
                    </div>
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsSaturday" /> Суббота
                    </div>
                    <div class="col-sm-12">
                        <input type="checkbox" asp-for="IsSunday" /> Воскресенье
                    </div>
                    <div class="col-xs-12"><button id="editDaysBtn" class="btn btn-primary">Сохранить</button></div>
                </div>
            </form>
        }

    </div>
</div>

TypiconOnline.Web/Views/ScheduleSettings/_ViewDaysPartial.cshtml
@model ScheduleSettingsWeekDaysModel

    <ul class="row list-group">
        @foreach (var elem in GetDays(Model))
        {
        <li class="list-group-item">@Html.Raw(elem)</li>
        }
    </ul>

@{
    IEnumerable<string> GetDays(ScheduleSettingsWeekDaysModel model)
    {
        var arr = new List<string>();

        if (model.IsMonday)
        {
            arr.Add("Понедельник");
        }
        if (model.IsTuesday)
        {
            arr.Add("Вторник");
        }
        if (model.IsWednesday)
        {
            arr.Add("Среда");
        }
        if (model.IsThursday)
        {
            arr.Add("Четверг");
        }
        if (model.IsFriday)
        {
            arr.Add("Пятница");
        }
        if (model.IsSaturday)
        {
            arr.Add("Суббота");
        }
        if (model.IsSunday)
        {
            arr.Add("Воскресенье");
        }

        if (arr.Count == 0)
        {
            arr.Add("<i class='fas fa-times icon-btn-danger'></i> Ни один день недели не отмечен");
        }
        else if (arr.Count == 7)
        {
            arr.Clear();
            arr.Add("<i class='fas fa-check icon-btn-success'></i> Богослужения совершаются каждый день");
        }

        return arr;
    }
}